pub const URL_JSON: &str = r##"
{
  "domain":[
    {
      "url":"https://thereport.be/drudge?check=1",
      "rtimeout":5000,
      "threshold":2,
      "check_interval":120,
      "dnd":false
    },
    {
      "url":"https://thereport.be/backend/parsedrudge?check=1",
      "rtimeout":20000,
      "threshold":10,
      "check_interval":120,
      "dnd":false
    },
    {
      "url":"https://thereport.be/backend/parsecitizen?check=1",
      "rtimeout":10000,
      "threshold":10,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://thereport.be/backend/parseliberty?check=1",
      "rtimeout":30000,
      "threshold":20,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://thereport.be/article/?u=https%3A%2F%2Fwww.foxnews.com%2Fpolitics%2Fringleader-gas-stove-crackdown-speak-house-democrats-annual-conference&check=1",
      "rtimeout":5000,
      "threshold":2,
      "check_interval":120,
      "dnd":false
    },
    {
      "url":"https://thereport.be/comment?u=http://rt.com/usa/265936-us-nuclear-strike-russia/&check=1",
      "rtimeout":5000,
      "threshold":2,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://breaking.iavian.net/breaking?nid=1&check=1",
      "rtimeout":5000,
      "threshold":2,
      "dnd":false
    },
    {
      "url":"https://tiny.iavian.net/d4gd?check",
      "rtimeout":5000,
      "threshold":2,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://thereport.be/apnsstats",
      "rtimeout":5000,
      "threshold":5,
      "check_interval":1200,
      "dnd":true
    },
    {
      "url":"https://play.google.com/store/apps/details?id=us.dreport.free",
      "rtimeout":5000,
      "threshold":5,
      "check_interval":600,
      "dnd":true
    },
    {
      "url":"https://play.google.com/store/apps/details?id=us.liberty.daily.free",
      "rtimeout":5000,
      "threshold":5,
      "check_interval":600,
      "dnd":true
    },
    {
      "url":"http://fivefilters.iavian.net/r.php?u=https://freebeacon.com/blog/human-cash-incinerator-jon-ossoff/",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":600,
      "dnd":true
    },
    {
      "url":"https://play.google.com/store/apps/details?id=instant.breaking.news.free",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":600,
      "dnd":true
    },
    {
      "url":"https://play.google.com/store/apps/details?id=the.report.us.free",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":600,
      "dnd":true
    },
    {
      "url":"https://expander.iavian.net/?url=https://tiny.iavian.net/1",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://img.thereport.be/img?w=100&url=https://media.washtimes.com/media/image/2020/06/14/virus_outbreak_new_york_story_59683.jpg",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"http://webkit.iavian.net:8080/open?source=f&url=https://www.theepochtimes.com/health/pasteurization-may-not-kill-bird-flu-in-milk-experts-5625870",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"http://webkit.iavian.net:8080/check",
      "rtimeout":5000,
      "threshold":10,
      "check_interval":120,
      "dnd":true
    },
    {
      "url":"https://iavian-upinger.fly.dev/health/article",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://iavian-upinger.fly.dev/health/breaking",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://iavian-upinger.fly.dev/health/webkit_fly_open",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://iavian-upinger.fly.dev/health/webkit_home_imac",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://iavian-upinger.fly.dev/health/webkit_home_macmini",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://img.thereport.be/img?w=320&url=https%3A%2F%2Fimages.americanthinker.com%2Fimported%2F2024-01%2F251500_800.jpeg",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    },
    {
      "url":"https://thereport.be/v2/ios/feed?f=4&f=27&f=40&f=24&f=38&f=11&f=45&f=42&f=31&f=44&f=33&f=23&f=10&f=16&f=46&f=48&f=3&f=12&f=9&f=34&f=22&f=17&f=41&f=21&f=26&f=15&f=35&f=19&f=29&f=28&f=8&f=43&f=37&f=5&f=30&f=25&f=1&f=36&f=18&f=6&f=7&f=39&f=20&f=32&f=2&f=13&f=14&f=47&f=100&f=0&",
      "rtimeout":5000,
      "threshold":10,
      "dnd":true,
      "empty":true
    }
  ]
}
"##;
